version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Porta padrão do Flask
    volumes:
      - ./src:/src  # Para desenvolvimento, permite atualizar o código sem reconstruir a imagem
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - TZ=America/Sao_Paulo
    hostname: python-app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:5000/api/v1/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
